# ================================================
# ALL ENVIRONMENTS
# ----------------
security:
  sessions: ALWAYS

multipart:
  max-file-size: 100MB
  max-request-size: 100MB

mail:
  host: smtp.gmail.com
  port: 587
  user: info@provesoft.com
  password: Pr0v3$0ftP@55w0rd;

token:
  expiry:
    recovery: 12
    registration: 24

# =================================================
# DEV SERVER
#-----------
server:
  port: 8080

logging:
  level: INFO

zuul:
  routes:
    ui:
      url: http://localhost:8081
      # Remote server deployment
      # url: http://provesoft.cantango.ca:8081
    resource:
      url: http://localhost:9000

url:
  abs: provesoft.cantango.ca

# ==================================================
# PRODUCTION SERVER
#------------------
#server:
#  port: 443
#    ssl:
#      key-store: /path/to/keystore/keystore.p12
#      key-store-password: mypassword
#      keyStoreType: PKCS12
#      keyAlias: myalias
#
#logging:
# level: WARN
#
#zuul:
#  routes:
#    ui:
#      url: https://localhost:8081
#      # Remote server deployment
#      # url: https://provesoft.com
#    resource:
#      url: https://localhost:9000
# Custom
#url:
#  abs: provesoft.com



