# =========================================
# DEV SERVER
# ----------
server:
  port: 8081
  address: 127.0.0.1

logging:
  level: INFO

url:
  abs: app.provesoft.com

# =========================================
# PRODUCTION SERVER
# ----------
#server:
#  port: 8081
#  ssl:
#      key-store: /path/to/keystore/keystore.p12
#      key-store-password: mypassword
#      keyStoreType: PKCS12
#      keyAlias: myalias
#
#logging:
#  level: WARN
#
#url:
# abs: app.provesoft.com
